# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: app-v1
#   namespace: default
# spec:
#   replicas: 3
#   selector:
#     matchLabels:
#       app: app
#       version: v1
#   template:
#     metadata:
#       labels:
#         app: app
#         version: v1
#     spec:
#       containers:
#         - name: app
#           image: nginx:stable
#           ports:
#             - containerPort: 80
